name = "penguin-timecard-astro"
compatibility_date = "2026-05-19"
pages_build_output_dir = "./dist"

[vars]
CONTACT_FROM_EMAIL = "Penguin Timecard <noreply@send.tc-timecard.com>"
CONTACT_TO_EMAIL = "timecard@transcommunica.com,kakisako.h@transcommunica.com"